FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD webapp.jar /opt/webapp/
EXPOSE 8080
WORKDIR /opt/webapp/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "webapp.jar"]
